FROM node:8-alpine

WORKDIR /app
RUN npm install nodemon -g
RUN npm install babel-cli -g

COPY package.json /app/package.json
COPY .babelrc /app/.babelrc

COPY ./server /app/server

RUN npm install

EXPOSE 3030