#version: '3'
#services:
#  db:
#    image: redis
#  kill-the-enemy-game-server:
#    build: .
#    volumes:
#     - ./:/app
#    ports:
#     - "3030:3030"
#    depends_on:
#     - db
#    command: nodemon --watch /app/server --exec babel-node /app/server/app.js --presets es2015

version: '2'
services:
  kill-the-enemy-game:
    build: .
    ports:
     - "3030:3030"
    depends_on:
     - redis
  redis:
    image: redis